[NotebookApp | WARNING] No nbgrader_config.py file found (rerun with --debug to see where nbgrader is looking)
[NotebookApp | INFO] Loading the validate_assignment nbgrader serverextension
[NotebookApp | INFO] Serving notebooks from local directory: /Users/sherryleo/Documents/course/Project with Ugur/healthcare-predictive
[NotebookApp | INFO] 0 active kernels 
[NotebookApp | INFO] The Jupyter Notebook is running at: http://localhost:8888/?token=a2406a657d0afc54d60038d4dd35c96694e7aa546f3c6b6f
[NotebookApp | INFO] Use Control-C to stop this server and shut down all kernels (twice to skip confirmation).
[NotebookApp | CRITICAL] 
    
    Copy/paste this URL into your browser when you connect for the first time,
    to login with a token:
        http://localhost:8888/?token=a2406a657d0afc54d60038d4dd35c96694e7aa546f3c6b6f
[NotebookApp | INFO] Accepting one-time-token-authenticated connection from ::1
[NotebookApp | WARNING] No nbgrader_config.py file found. Rerun with DEBUG log level to see where nbgrader is looking.
[NotebookApp | CRITICAL] Unwritable directory, please contact your instructor: /srv/nbgrader/exchange
[NotebookApp | ERROR] Traceback (most recent call last):
      File "/Users/sherryleo/anaconda/lib/python3.6/site-packages/nbgrader/server_extensions/assignment_list/handlers.py", line 63, in list_released_assignments
        assignments = lister.start()
      File "/Users/sherryleo/anaconda/lib/python3.6/site-packages/nbgrader/exchange/list.py", line 129, in start
        super(ExchangeList, self).start()
      File "/Users/sherryleo/anaconda/lib/python3.6/site-packages/nbgrader/exchange/exchange.py", line 122, in start
        self.ensure_root()
      File "/Users/sherryleo/anaconda/lib/python3.6/site-packages/nbgrader/exchange/exchange.py", line 100, in ensure_root
        self.fail("Unwritable directory, please contact your instructor: {}".format(self.root))
      File "/Users/sherryleo/anaconda/lib/python3.6/site-packages/nbgrader/exchange/exchange.py", line 78, in fail
        raise ExchangeError(msg)
    nbgrader.exchange.exchange.ExchangeError: Unwritable directory, please contact your instructor: /srv/nbgrader/exchange
    
[NotebookApp | WARNING] 404 GET /demo.gif (::1) 21.69ms referer=http://localhost:8888/tree
[NotebookApp | WARNING] No nbgrader_config.py file found. Rerun with DEBUG log level to see where nbgrader is looking.
[NotebookApp | CRITICAL] Unwritable directory, please contact your instructor: /srv/nbgrader/exchange
[NotebookApp | ERROR] Traceback (most recent call last):
      File "/Users/sherryleo/anaconda/lib/python3.6/site-packages/nbgrader/server_extensions/assignment_list/handlers.py", line 63, in list_released_assignments
        assignments = lister.start()
      File "/Users/sherryleo/anaconda/lib/python3.6/site-packages/nbgrader/exchange/list.py", line 129, in start
        super(ExchangeList, self).start()
      File "/Users/sherryleo/anaconda/lib/python3.6/site-packages/nbgrader/exchange/exchange.py", line 122, in start
        self.ensure_root()
      File "/Users/sherryleo/anaconda/lib/python3.6/site-packages/nbgrader/exchange/exchange.py", line 100, in ensure_root
        self.fail("Unwritable directory, please contact your instructor: {}".format(self.root))
      File "/Users/sherryleo/anaconda/lib/python3.6/site-packages/nbgrader/exchange/exchange.py", line 78, in fail
        raise ExchangeError(msg)
    nbgrader.exchange.exchange.ExchangeError: Unwritable directory, please contact your instructor: /srv/nbgrader/exchange
    
[NotebookApp | WARNING] 404 GET /tree/demo.gif (::1) 3.07ms referer=http://localhost:8888/tree/notebooks
[NotebookApp | WARNING] Notebook notebooks/LSTM Multivariate Forecasting.ipynb is not trusted
[NotebookApp | INFO] Kernel started: 8c2d43b4-8fb2-4988-945e-b630b718f7fc
[NotebookApp | INFO] Kernel restarted: 8c2d43b4-8fb2-4988-945e-b630b718f7fc
[NotebookApp | INFO] Saving file at /notebooks/LSTM Multivariate Forecasting.ipynb
[NotebookApp | INFO] Saving file at /notebooks/LSTM Multivariate Forecasting.ipynb
[NotebookApp | INFO] Kernel restarted: 8c2d43b4-8fb2-4988-945e-b630b718f7fc
[NotebookApp | INFO] Saving file at /notebooks/LSTM Multivariate Forecasting.ipynb
[NotebookApp | INFO] Saving file at /notebooks/LSTM Multivariate Forecasting.ipynb
[NotebookApp | INFO] Saving file at /notebooks/LSTM Multivariate Forecasting.ipynb
[NotebookApp | INFO] Kernel restarted: 8c2d43b4-8fb2-4988-945e-b630b718f7fc
[NotebookApp | INFO] Saving file at /notebooks/LSTM Multivariate Forecasting.ipynb
[NotebookApp | INFO] Kernel restarted: 8c2d43b4-8fb2-4988-945e-b630b718f7fc
[NotebookApp | INFO] Saving file at /notebooks/LSTM Multivariate Forecasting.ipynb
[NotebookApp | WARNING] No nbgrader_config.py file found (rerun with --debug to see where nbgrader is looking)
[NotebookApp | INFO] Loading the validate_assignment nbgrader serverextension
[NotebookApp | INFO] Serving notebooks from local directory: /Users/sherryleo/Documents/course/Project with Ugur/healthcare-predictive
[NotebookApp | INFO] 0 active kernels 
[NotebookApp | INFO] The Jupyter Notebook is running at: http://localhost:8889/?token=c7619ec525de744efb3faa887bd7fffd3d005ea3f52f2b09
[NotebookApp | INFO] Use Control-C to stop this server and shut down all kernels (twice to skip confirmation).
[NotebookApp | CRITICAL] 
    
    Copy/paste this URL into your browser when you connect for the first time,
    to login with a token:
        http://localhost:8889/?token=c7619ec525de744efb3faa887bd7fffd3d005ea3f52f2b09
[NotebookApp | INFO] Accepting one-time-token-authenticated connection from ::1
[NotebookApp | WARNING] No nbgrader_config.py file found. Rerun with DEBUG log level to see where nbgrader is looking.
[NotebookApp | CRITICAL] Unwritable directory, please contact your instructor: /srv/nbgrader/exchange
[NotebookApp | ERROR] Traceback (most recent call last):
      File "/Users/sherryleo/anaconda/lib/python3.6/site-packages/nbgrader/server_extensions/assignment_list/handlers.py", line 63, in list_released_assignments
        assignments = lister.start()
      File "/Users/sherryleo/anaconda/lib/python3.6/site-packages/nbgrader/exchange/list.py", line 129, in start
        super(ExchangeList, self).start()
      File "/Users/sherryleo/anaconda/lib/python3.6/site-packages/nbgrader/exchange/exchange.py", line 122, in start
        self.ensure_root()
      File "/Users/sherryleo/anaconda/lib/python3.6/site-packages/nbgrader/exchange/exchange.py", line 100, in ensure_root
        self.fail("Unwritable directory, please contact your instructor: {}".format(self.root))
      File "/Users/sherryleo/anaconda/lib/python3.6/site-packages/nbgrader/exchange/exchange.py", line 78, in fail
        raise ExchangeError(msg)
    nbgrader.exchange.exchange.ExchangeError: Unwritable directory, please contact your instructor: /srv/nbgrader/exchange
    
[NotebookApp | WARNING] 404 GET /demo.gif (::1) 18.98ms referer=http://localhost:8889/tree
[NotebookApp | WARNING] No nbgrader_config.py file found. Rerun with DEBUG log level to see where nbgrader is looking.
[NotebookApp | CRITICAL] Unwritable directory, please contact your instructor: /srv/nbgrader/exchange
[NotebookApp | ERROR] Traceback (most recent call last):
      File "/Users/sherryleo/anaconda/lib/python3.6/site-packages/nbgrader/server_extensions/assignment_list/handlers.py", line 63, in list_released_assignments
        assignments = lister.start()
      File "/Users/sherryleo/anaconda/lib/python3.6/site-packages/nbgrader/exchange/list.py", line 129, in start
        super(ExchangeList, self).start()
      File "/Users/sherryleo/anaconda/lib/python3.6/site-packages/nbgrader/exchange/exchange.py", line 122, in start
        self.ensure_root()
      File "/Users/sherryleo/anaconda/lib/python3.6/site-packages/nbgrader/exchange/exchange.py", line 100, in ensure_root
        self.fail("Unwritable directory, please contact your instructor: {}".format(self.root))
      File "/Users/sherryleo/anaconda/lib/python3.6/site-packages/nbgrader/exchange/exchange.py", line 78, in fail
        raise ExchangeError(msg)
    nbgrader.exchange.exchange.ExchangeError: Unwritable directory, please contact your instructor: /srv/nbgrader/exchange
    
[NotebookApp | WARNING] 404 GET /tree/demo.gif (::1) 3.68ms referer=http://localhost:8889/tree/notebooks
[NotebookApp | INFO] Kernel started: 7b3e0308-9cea-4b39-bd08-cf337d16c56e
[NotebookApp | INFO] Saving file at /notebooks/LSTM Multivariate Forecasting.ipynb
[NotebookApp | INFO] interrupted
[NotebookApp | INFO] interrupted
[NotebookApp | CRITICAL] Shutdown confirmed
[NotebookApp | INFO] Shutting down kernels
[NotebookApp | INFO] Kernel shutdown: 7b3e0308-9cea-4b39-bd08-cf337d16c56e
[NotebookApp | WARNING] No nbgrader_config.py file found (rerun with --debug to see where nbgrader is looking)
[NotebookApp | INFO] Loading the validate_assignment nbgrader serverextension
[NotebookApp | INFO] Serving notebooks from local directory: /Users/sherryleo/Documents/course/Project with Ugur/healthcare-predictive
[NotebookApp | INFO] 0 active kernels 
[NotebookApp | INFO] The Jupyter Notebook is running at: http://localhost:8889/?token=1925d1b12c8891cec35c5ba42f4cb650fb42d550fbf8fa17
[NotebookApp | INFO] Use Control-C to stop this server and shut down all kernels (twice to skip confirmation).
[NotebookApp | CRITICAL] 
    
    Copy/paste this URL into your browser when you connect for the first time,
    to login with a token:
        http://localhost:8889/?token=1925d1b12c8891cec35c5ba42f4cb650fb42d550fbf8fa17
[NotebookApp | INFO] Accepting one-time-token-authenticated connection from ::1
[NotebookApp | WARNING] No nbgrader_config.py file found. Rerun with DEBUG log level to see where nbgrader is looking.
[NotebookApp | CRITICAL] Unwritable directory, please contact your instructor: /srv/nbgrader/exchange
[NotebookApp | ERROR] Traceback (most recent call last):
      File "/Users/sherryleo/anaconda/lib/python3.6/site-packages/nbgrader/server_extensions/assignment_list/handlers.py", line 63, in list_released_assignments
        assignments = lister.start()
      File "/Users/sherryleo/anaconda/lib/python3.6/site-packages/nbgrader/exchange/list.py", line 129, in start
        super(ExchangeList, self).start()
      File "/Users/sherryleo/anaconda/lib/python3.6/site-packages/nbgrader/exchange/exchange.py", line 122, in start
        self.ensure_root()
      File "/Users/sherryleo/anaconda/lib/python3.6/site-packages/nbgrader/exchange/exchange.py", line 100, in ensure_root
        self.fail("Unwritable directory, please contact your instructor: {}".format(self.root))
      File "/Users/sherryleo/anaconda/lib/python3.6/site-packages/nbgrader/exchange/exchange.py", line 78, in fail
        raise ExchangeError(msg)
    nbgrader.exchange.exchange.ExchangeError: Unwritable directory, please contact your instructor: /srv/nbgrader/exchange
    
[NotebookApp | WARNING] 404 GET /demo.gif (::1) 16.36ms referer=http://localhost:8889/tree
[NotebookApp | WARNING] No nbgrader_config.py file found. Rerun with DEBUG log level to see where nbgrader is looking.
[NotebookApp | CRITICAL] Unwritable directory, please contact your instructor: /srv/nbgrader/exchange
[NotebookApp | ERROR] Traceback (most recent call last):
      File "/Users/sherryleo/anaconda/lib/python3.6/site-packages/nbgrader/server_extensions/assignment_list/handlers.py", line 63, in list_released_assignments
        assignments = lister.start()
      File "/Users/sherryleo/anaconda/lib/python3.6/site-packages/nbgrader/exchange/list.py", line 129, in start
        super(ExchangeList, self).start()
      File "/Users/sherryleo/anaconda/lib/python3.6/site-packages/nbgrader/exchange/exchange.py", line 122, in start
        self.ensure_root()
      File "/Users/sherryleo/anaconda/lib/python3.6/site-packages/nbgrader/exchange/exchange.py", line 100, in ensure_root
        self.fail("Unwritable directory, please contact your instructor: {}".format(self.root))
      File "/Users/sherryleo/anaconda/lib/python3.6/site-packages/nbgrader/exchange/exchange.py", line 78, in fail
        raise ExchangeError(msg)
    nbgrader.exchange.exchange.ExchangeError: Unwritable directory, please contact your instructor: /srv/nbgrader/exchange
    
[NotebookApp | WARNING] No nbgrader_config.py file found. Rerun with DEBUG log level to see where nbgrader is looking.
[NotebookApp | CRITICAL] Unwritable directory, please contact your instructor: /srv/nbgrader/exchange
[NotebookApp | ERROR] Traceback (most recent call last):
      File "/Users/sherryleo/anaconda/lib/python3.6/site-packages/nbgrader/server_extensions/assignment_list/handlers.py", line 63, in list_released_assignments
        assignments = lister.start()
      File "/Users/sherryleo/anaconda/lib/python3.6/site-packages/nbgrader/exchange/list.py", line 129, in start
        super(ExchangeList, self).start()
      File "/Users/sherryleo/anaconda/lib/python3.6/site-packages/nbgrader/exchange/exchange.py", line 122, in start
        self.ensure_root()
      File "/Users/sherryleo/anaconda/lib/python3.6/site-packages/nbgrader/exchange/exchange.py", line 100, in ensure_root
        self.fail("Unwritable directory, please contact your instructor: {}".format(self.root))
      File "/Users/sherryleo/anaconda/lib/python3.6/site-packages/nbgrader/exchange/exchange.py", line 78, in fail
        raise ExchangeError(msg)
    nbgrader.exchange.exchange.ExchangeError: Unwritable directory, please contact your instructor: /srv/nbgrader/exchange
    
[NotebookApp | WARNING] 404 GET /tree/demo.gif (::1) 2.62ms referer=http://localhost:8889/tree/notebooks
[NotebookApp | INFO] Kernel started: fc853778-88e3-430c-824e-53ff1fba57bf
[NotebookApp | INFO] Saving file at /notebooks/LSTM Multivariate Forecasting.ipynb
[NotebookApp | INFO] Saving file at /notebooks/LSTM Multivariate Forecasting.ipynb
[NotebookApp | INFO] interrupted
[NotebookApp | CRITICAL] Shutdown confirmed
[NotebookApp | INFO] Shutting down kernels
[NotebookApp | INFO] Kernel shutdown: fc853778-88e3-430c-824e-53ff1fba57bf
[NotebookApp | WARNING] No nbgrader_config.py file found (rerun with --debug to see where nbgrader is looking)
[NotebookApp | INFO] Loading the validate_assignment nbgrader serverextension
[NotebookApp | INFO] Serving notebooks from local directory: /Users/sherryleo/Documents/course/Project with Ugur/healthcare-predictive
[NotebookApp | INFO] 0 active kernels 
[NotebookApp | INFO] The Jupyter Notebook is running at: http://localhost:8889/?token=8251d0b0e593b9fa31c63ef1ed533c97ea0dc72f098e9090
[NotebookApp | INFO] Use Control-C to stop this server and shut down all kernels (twice to skip confirmation).
[NotebookApp | CRITICAL] 
    
    Copy/paste this URL into your browser when you connect for the first time,
    to login with a token:
        http://localhost:8889/?token=8251d0b0e593b9fa31c63ef1ed533c97ea0dc72f098e9090
[NotebookApp | INFO] Accepting one-time-token-authenticated connection from ::1
[NotebookApp | WARNING] No nbgrader_config.py file found. Rerun with DEBUG log level to see where nbgrader is looking.
[NotebookApp | CRITICAL] Unwritable directory, please contact your instructor: /srv/nbgrader/exchange
[NotebookApp | ERROR] Traceback (most recent call last):
      File "/Users/sherryleo/anaconda/lib/python3.6/site-packages/nbgrader/server_extensions/assignment_list/handlers.py", line 63, in list_released_assignments
        assignments = lister.start()
      File "/Users/sherryleo/anaconda/lib/python3.6/site-packages/nbgrader/exchange/list.py", line 129, in start
        super(ExchangeList, self).start()
      File "/Users/sherryleo/anaconda/lib/python3.6/site-packages/nbgrader/exchange/exchange.py", line 122, in start
        self.ensure_root()
      File "/Users/sherryleo/anaconda/lib/python3.6/site-packages/nbgrader/exchange/exchange.py", line 100, in ensure_root
        self.fail("Unwritable directory, please contact your instructor: {}".format(self.root))
      File "/Users/sherryleo/anaconda/lib/python3.6/site-packages/nbgrader/exchange/exchange.py", line 78, in fail
        raise ExchangeError(msg)
    nbgrader.exchange.exchange.ExchangeError: Unwritable directory, please contact your instructor: /srv/nbgrader/exchange
    
[NotebookApp | WARNING] 404 GET /demo.gif (::1) 17.94ms referer=http://localhost:8889/tree
[NotebookApp | WARNING] No nbgrader_config.py file found. Rerun with DEBUG log level to see where nbgrader is looking.
[NotebookApp | CRITICAL] Unwritable directory, please contact your instructor: /srv/nbgrader/exchange
[NotebookApp | ERROR] Traceback (most recent call last):
      File "/Users/sherryleo/anaconda/lib/python3.6/site-packages/nbgrader/server_extensions/assignment_list/handlers.py", line 63, in list_released_assignments
        assignments = lister.start()
      File "/Users/sherryleo/anaconda/lib/python3.6/site-packages/nbgrader/exchange/list.py", line 129, in start
        super(ExchangeList, self).start()
      File "/Users/sherryleo/anaconda/lib/python3.6/site-packages/nbgrader/exchange/exchange.py", line 122, in start
        self.ensure_root()
      File "/Users/sherryleo/anaconda/lib/python3.6/site-packages/nbgrader/exchange/exchange.py", line 100, in ensure_root
        self.fail("Unwritable directory, please contact your instructor: {}".format(self.root))
      File "/Users/sherryleo/anaconda/lib/python3.6/site-packages/nbgrader/exchange/exchange.py", line 78, in fail
        raise ExchangeError(msg)
    nbgrader.exchange.exchange.ExchangeError: Unwritable directory, please contact your instructor: /srv/nbgrader/exchange
    
[NotebookApp | WARNING] 404 GET /tree/demo.gif (::1) 2.85ms referer=http://localhost:8889/tree/notebooks
[NotebookApp | INFO] Kernel started: 8c1dcf45-3db5-4868-ae6e-ed4e165e6d22
[NotebookApp | INFO] Kernel restarted: 8c1dcf45-3db5-4868-ae6e-ed4e165e6d22
[NotebookApp | INFO] Saving file at /notebooks/LSTM Multivariate Forecasting.ipynb
[NotebookApp | INFO] interrupted
[NotebookApp | CRITICAL] Shutdown confirmed
[NotebookApp | INFO] Shutting down kernels
[NotebookApp | INFO] Kernel shutdown: 8c1dcf45-3db5-4868-ae6e-ed4e165e6d22
[NotebookApp | WARNING] No nbgrader_config.py file found (rerun with --debug to see where nbgrader is looking)
[NotebookApp | INFO] Loading the validate_assignment nbgrader serverextension
[NotebookApp | INFO] Serving notebooks from local directory: /Users/sherryleo/Documents/course/Project with Ugur/healthcare-predictive
[NotebookApp | INFO] 0 active kernels 
[NotebookApp | INFO] The Jupyter Notebook is running at: http://localhost:8888/?token=9d6acb5e08e241196f9a9fbff1ddf39959f1c3a279444e93
[NotebookApp | INFO] Use Control-C to stop this server and shut down all kernels (twice to skip confirmation).
[NotebookApp | CRITICAL] 
    
    Copy/paste this URL into your browser when you connect for the first time,
    to login with a token:
        http://localhost:8888/?token=9d6acb5e08e241196f9a9fbff1ddf39959f1c3a279444e93
[NotebookApp | INFO] Accepting one-time-token-authenticated connection from ::1
[NotebookApp | WARNING] No nbgrader_config.py file found. Rerun with DEBUG log level to see where nbgrader is looking.
[NotebookApp | CRITICAL] Unwritable directory, please contact your instructor: /srv/nbgrader/exchange
[NotebookApp | ERROR] Traceback (most recent call last):
      File "/Users/sherryleo/anaconda/lib/python3.6/site-packages/nbgrader/server_extensions/assignment_list/handlers.py", line 63, in list_released_assignments
        assignments = lister.start()
      File "/Users/sherryleo/anaconda/lib/python3.6/site-packages/nbgrader/exchange/list.py", line 129, in start
        super(ExchangeList, self).start()
      File "/Users/sherryleo/anaconda/lib/python3.6/site-packages/nbgrader/exchange/exchange.py", line 122, in start
        self.ensure_root()
      File "/Users/sherryleo/anaconda/lib/python3.6/site-packages/nbgrader/exchange/exchange.py", line 100, in ensure_root
        self.fail("Unwritable directory, please contact your instructor: {}".format(self.root))
      File "/Users/sherryleo/anaconda/lib/python3.6/site-packages/nbgrader/exchange/exchange.py", line 78, in fail
        raise ExchangeError(msg)
    nbgrader.exchange.exchange.ExchangeError: Unwritable directory, please contact your instructor: /srv/nbgrader/exchange
    
[NotebookApp | WARNING] 404 GET /demo.gif (::1) 11.20ms referer=http://localhost:8888/tree
[NotebookApp | WARNING] No nbgrader_config.py file found. Rerun with DEBUG log level to see where nbgrader is looking.
[NotebookApp | CRITICAL] Unwritable directory, please contact your instructor: /srv/nbgrader/exchange
[NotebookApp | ERROR] Traceback (most recent call last):
      File "/Users/sherryleo/anaconda/lib/python3.6/site-packages/nbgrader/server_extensions/assignment_list/handlers.py", line 63, in list_released_assignments
        assignments = lister.start()
      File "/Users/sherryleo/anaconda/lib/python3.6/site-packages/nbgrader/exchange/list.py", line 129, in start
        super(ExchangeList, self).start()
      File "/Users/sherryleo/anaconda/lib/python3.6/site-packages/nbgrader/exchange/exchange.py", line 122, in start
        self.ensure_root()
      File "/Users/sherryleo/anaconda/lib/python3.6/site-packages/nbgrader/exchange/exchange.py", line 100, in ensure_root
        self.fail("Unwritable directory, please contact your instructor: {}".format(self.root))
      File "/Users/sherryleo/anaconda/lib/python3.6/site-packages/nbgrader/exchange/exchange.py", line 78, in fail
        raise ExchangeError(msg)
    nbgrader.exchange.exchange.ExchangeError: Unwritable directory, please contact your instructor: /srv/nbgrader/exchange
    
[NotebookApp | WARNING] 404 GET /tree/demo.gif (::1) 1.41ms referer=http://localhost:8888/tree/Visualization
[NotebookApp | WARNING] No nbgrader_config.py file found. Rerun with DEBUG log level to see where nbgrader is looking.
[NotebookApp | CRITICAL] Unwritable directory, please contact your instructor: /srv/nbgrader/exchange
[NotebookApp | ERROR] Traceback (most recent call last):
      File "/Users/sherryleo/anaconda/lib/python3.6/site-packages/nbgrader/server_extensions/assignment_list/handlers.py", line 63, in list_released_assignments
        assignments = lister.start()
      File "/Users/sherryleo/anaconda/lib/python3.6/site-packages/nbgrader/exchange/list.py", line 129, in start
        super(ExchangeList, self).start()
      File "/Users/sherryleo/anaconda/lib/python3.6/site-packages/nbgrader/exchange/exchange.py", line 122, in start
        self.ensure_root()
      File "/Users/sherryleo/anaconda/lib/python3.6/site-packages/nbgrader/exchange/exchange.py", line 100, in ensure_root
        self.fail("Unwritable directory, please contact your instructor: {}".format(self.root))
      File "/Users/sherryleo/anaconda/lib/python3.6/site-packages/nbgrader/exchange/exchange.py", line 78, in fail
        raise ExchangeError(msg)
    nbgrader.exchange.exchange.ExchangeError: Unwritable directory, please contact your instructor: /srv/nbgrader/exchange
    
[NotebookApp | WARNING] 404 GET /tree/demo.gif (::1) 1.27ms referer=http://localhost:8888/tree/notebooks
[NotebookApp | INFO] Kernel started: bcce50f8-5bfb-4b22-9b0d-8cd394e41828
[NotebookApp | INFO] Kernel started: 8cea3573-ccd8-4955-9ec6-fd8126761213
[NotebookApp | INFO] Kernel restarted: bcce50f8-5bfb-4b22-9b0d-8cd394e41828
[NotebookApp | INFO] Saving file at /notebooks/Calculate good quality data ratio.ipynb
[NotebookApp | INFO] Saving file at /notebooks/Calculate good quality data ratio.ipynb
[NotebookApp | INFO] Saving file at /notebooks/Calculate good quality data ratio.ipynb
[NotebookApp | INFO] Saving file at /notebooks/Calculate good quality data ratio.ipynb
[NotebookApp | INFO] Saving file at /notebooks/Calculate good quality data ratio.ipynb
[NotebookApp | INFO] Saving file at /notebooks/Calculate good quality data ratio.ipynb
[NotebookApp | INFO] Saving file at /notebooks/Calculate good quality data ratio.ipynb
[NotebookApp | INFO] Saving file at /notebooks/Calculate good quality data ratio.ipynb
[NotebookApp | INFO] Saving file at /notebooks/Calculate good quality data ratio.ipynb
[NotebookApp | INFO] Saving file at /notebooks/Calculate good quality data ratio.ipynb
[NotebookApp | INFO] Kernel restarted: bcce50f8-5bfb-4b22-9b0d-8cd394e41828
[NotebookApp | INFO] Saving file at /notebooks/Calculate good quality data ratio.ipynb
[NotebookApp | INFO] Kernel restarted: bcce50f8-5bfb-4b22-9b0d-8cd394e41828
[NotebookApp | INFO] Saving file at /notebooks/Calculate good quality data ratio.ipynb
[NotebookApp | INFO] Saving file at /notebooks/Calculate good quality data ratio.ipynb
[NotebookApp | INFO] Saving file at /notebooks/Calculate good quality data ratio.ipynb
[NotebookApp | INFO] Saving file at /notebooks/Calculate good quality data ratio.ipynb
[NotebookApp | INFO] Saving file at /notebooks/Calculate good quality data ratio.ipynb
[NotebookApp | INFO] Saving file at /notebooks/Calculate good quality data ratio.ipynb
[NotebookApp | INFO] Saving file at /notebooks/Calculate good quality data ratio.ipynb
[NotebookApp | INFO] Saving file at /notebooks/Calculate good quality data ratio.ipynb
[NotebookApp | INFO] Saving file at /notebooks/Calculate good quality data ratio.ipynb
[NotebookApp | INFO] Saving file at /notebooks/Calculate good quality data ratio.ipynb
[NotebookApp | INFO] Kernel restarted: bcce50f8-5bfb-4b22-9b0d-8cd394e41828
[NotebookApp | INFO] Saving file at /notebooks/Calculate good quality data ratio.ipynb
[NotebookApp | INFO] Saving file at /notebooks/Calculate good quality data ratio.ipynb
[NotebookApp | INFO] Saving file at /notebooks/Calculate good quality data ratio.ipynb
[NotebookApp | INFO] Saving file at /notebooks/Calculate good quality data ratio.ipynb
[NotebookApp | INFO] Saving file at /notebooks/Calculate good quality data ratio.ipynb
[NotebookApp | INFO] Saving file at /notebooks/Calculate good quality data ratio.ipynb
[NotebookApp | INFO] Saving file at /notebooks/Calculate good quality data ratio.ipynb
[NotebookApp | INFO] Saving file at /notebooks/Calculate good quality data ratio.ipynb
[NotebookApp | INFO] Saving file at /notebooks/Calculate good quality data ratio.ipynb
[NotebookApp | INFO] Kernel restarted: bcce50f8-5bfb-4b22-9b0d-8cd394e41828
[NotebookApp | INFO] Saving file at /notebooks/Calculate good quality data ratio.ipynb
[NotebookApp | INFO] Saving file at /notebooks/Calculate good quality data ratio.ipynb
[NotebookApp | INFO] Saving file at /notebooks/Calculate good quality data ratio.ipynb
[NotebookApp | INFO] Saving file at /notebooks/Calculate good quality data ratio.ipynb
[NotebookApp | INFO] Saving file at /notebooks/Calculate good quality data ratio.ipynb
[NotebookApp | INFO] Kernel restarted: bcce50f8-5bfb-4b22-9b0d-8cd394e41828
[NotebookApp | INFO] Kernel interrupted: bcce50f8-5bfb-4b22-9b0d-8cd394e41828
[NotebookApp | INFO] Kernel restarted: bcce50f8-5bfb-4b22-9b0d-8cd394e41828
[NotebookApp | INFO] Saving file at /notebooks/Calculate good quality data ratio.ipynb
[NotebookApp | INFO] Saving file at /notebooks/Calculate good quality data ratio.ipynb
[NotebookApp | INFO] Saving file at /notebooks/Calculate good quality data ratio.ipynb
[NotebookApp | INFO] Saving file at /notebooks/Calculate good quality data ratio.ipynb
[NotebookApp | INFO] Saving file at /notebooks/Calculate good quality data ratio.ipynb
[NotebookApp | INFO] Saving file at /notebooks/Calculate good quality data ratio.ipynb
[NotebookApp | INFO] Saving file at /notebooks/Calculate good quality data ratio.ipynb
[NotebookApp | INFO] Saving file at /notebooks/Calculate good quality data ratio.ipynb
[NotebookApp | INFO] Saving file at /notebooks/Calculate good quality data ratio.ipynb
[NotebookApp | INFO] Saving file at /notebooks/Calculate good quality data ratio.ipynb
[NotebookApp | INFO] Saving file at /notebooks/Calculate good quality data ratio.ipynb
[NotebookApp | INFO] interrupted
[NotebookApp | CRITICAL] Shutdown confirmed
[NotebookApp | INFO] Shutting down kernels
[NotebookApp | INFO] Kernel shutdown: bcce50f8-5bfb-4b22-9b0d-8cd394e41828
[NotebookApp | INFO] Kernel shutdown: 8cea3573-ccd8-4955-9ec6-fd8126761213
[NotebookApp | WARNING] No nbgrader_config.py file found (rerun with --debug to see where nbgrader is looking)
[NotebookApp | INFO] Loading the validate_assignment nbgrader serverextension
[NotebookApp | INFO] Serving notebooks from local directory: /Users/sherryleo/Documents/course/Project with Ugur/healthcare-predictive
[NotebookApp | INFO] 0 active kernels 
[NotebookApp | INFO] The Jupyter Notebook is running at: http://localhost:8888/?token=571820919b2f4f74f4a81e86391ce3b231f2c85cc0078836
[NotebookApp | INFO] Use Control-C to stop this server and shut down all kernels (twice to skip confirmation).
[NotebookApp | CRITICAL] 
    
    Copy/paste this URL into your browser when you connect for the first time,
    to login with a token:
        http://localhost:8888/?token=571820919b2f4f74f4a81e86391ce3b231f2c85cc0078836
[NotebookApp | INFO] Accepting one-time-token-authenticated connection from ::1
[NotebookApp | WARNING] No nbgrader_config.py file found. Rerun with DEBUG log level to see where nbgrader is looking.
[NotebookApp | CRITICAL] Unwritable directory, please contact your instructor: /srv/nbgrader/exchange
[NotebookApp | ERROR] Traceback (most recent call last):
      File "/Users/sherryleo/anaconda/lib/python3.6/site-packages/nbgrader/server_extensions/assignment_list/handlers.py", line 63, in list_released_assignments
        assignments = lister.start()
      File "/Users/sherryleo/anaconda/lib/python3.6/site-packages/nbgrader/exchange/list.py", line 129, in start
        super(ExchangeList, self).start()
      File "/Users/sherryleo/anaconda/lib/python3.6/site-packages/nbgrader/exchange/exchange.py", line 122, in start
        self.ensure_root()
      File "/Users/sherryleo/anaconda/lib/python3.6/site-packages/nbgrader/exchange/exchange.py", line 100, in ensure_root
        self.fail("Unwritable directory, please contact your instructor: {}".format(self.root))
      File "/Users/sherryleo/anaconda/lib/python3.6/site-packages/nbgrader/exchange/exchange.py", line 78, in fail
        raise ExchangeError(msg)
    nbgrader.exchange.exchange.ExchangeError: Unwritable directory, please contact your instructor: /srv/nbgrader/exchange
    
[NotebookApp | WARNING] 404 GET /demo.gif (::1) 16.31ms referer=http://localhost:8888/tree
[NotebookApp | WARNING] No nbgrader_config.py file found. Rerun with DEBUG log level to see where nbgrader is looking.
[NotebookApp | CRITICAL] Unwritable directory, please contact your instructor: /srv/nbgrader/exchange
[NotebookApp | ERROR] Traceback (most recent call last):
      File "/Users/sherryleo/anaconda/lib/python3.6/site-packages/nbgrader/server_extensions/assignment_list/handlers.py", line 63, in list_released_assignments
        assignments = lister.start()
      File "/Users/sherryleo/anaconda/lib/python3.6/site-packages/nbgrader/exchange/list.py", line 129, in start
        super(ExchangeList, self).start()
      File "/Users/sherryleo/anaconda/lib/python3.6/site-packages/nbgrader/exchange/exchange.py", line 122, in start
        self.ensure_root()
      File "/Users/sherryleo/anaconda/lib/python3.6/site-packages/nbgrader/exchange/exchange.py", line 100, in ensure_root
        self.fail("Unwritable directory, please contact your instructor: {}".format(self.root))
      File "/Users/sherryleo/anaconda/lib/python3.6/site-packages/nbgrader/exchange/exchange.py", line 78, in fail
        raise ExchangeError(msg)
    nbgrader.exchange.exchange.ExchangeError: Unwritable directory, please contact your instructor: /srv/nbgrader/exchange
    
[NotebookApp | WARNING] No nbgrader_config.py file found. Rerun with DEBUG log level to see where nbgrader is looking.
[NotebookApp | CRITICAL] Unwritable directory, please contact your instructor: /srv/nbgrader/exchange
[NotebookApp | ERROR] Traceback (most recent call last):
      File "/Users/sherryleo/anaconda/lib/python3.6/site-packages/nbgrader/server_extensions/assignment_list/handlers.py", line 63, in list_released_assignments
        assignments = lister.start()
      File "/Users/sherryleo/anaconda/lib/python3.6/site-packages/nbgrader/exchange/list.py", line 129, in start
        super(ExchangeList, self).start()
      File "/Users/sherryleo/anaconda/lib/python3.6/site-packages/nbgrader/exchange/exchange.py", line 122, in start
        self.ensure_root()
      File "/Users/sherryleo/anaconda/lib/python3.6/site-packages/nbgrader/exchange/exchange.py", line 100, in ensure_root
        self.fail("Unwritable directory, please contact your instructor: {}".format(self.root))
      File "/Users/sherryleo/anaconda/lib/python3.6/site-packages/nbgrader/exchange/exchange.py", line 78, in fail
        raise ExchangeError(msg)
    nbgrader.exchange.exchange.ExchangeError: Unwritable directory, please contact your instructor: /srv/nbgrader/exchange
    
[NotebookApp | WARNING] 404 GET /tree/demo.gif (::1) 3.85ms referer=http://localhost:8888/tree/notebooks
[NotebookApp | INFO] Kernel started: e974a402-0fc1-4da6-b432-df33ed61b550
[NotebookApp | INFO] Kernel started: 452b11c6-2434-41b3-bbdc-467f9a8e2f37
[NotebookApp | INFO] Kernel restarted: e974a402-0fc1-4da6-b432-df33ed61b550
[NotebookApp | INFO] Saving file at /notebooks/Calculate good quality data ratio.ipynb
[NotebookApp | INFO] Saving file at /notebooks/Calculate good quality data ratio.ipynb
[NotebookApp | INFO] Kernel interrupted: e974a402-0fc1-4da6-b432-df33ed61b550
[NotebookApp | INFO] Kernel restarted: e974a402-0fc1-4da6-b432-df33ed61b550
[NotebookApp | INFO] Saving file at /notebooks/Calculate good quality data ratio.ipynb
[NotebookApp | INFO] Saving file at /notebooks/Calculate good quality data ratio.ipynb
[NotebookApp | INFO] Kernel started: 20a0c79f-0cd2-48d8-a663-c265393b1960
[NotebookApp | INFO] Kernel started: 8197d994-b182-4702-aafc-d0dff2cb9af5
[NotebookApp | INFO] Saving file at /notebooks/Calculate good quality data ratio.ipynb
[NotebookApp | INFO] Saving file at /notebooks/Calculate good quality data ratio.ipynb
[NotebookApp | INFO] Saving file at /notebooks/Calculate good quality data ratio.ipynb
[NotebookApp | INFO] Saving file at /notebooks/Calculate good quality data ratio.ipynb
[NotebookApp | INFO] Kernel restarted: 8197d994-b182-4702-aafc-d0dff2cb9af5
[NotebookApp | INFO] Saving file at /notebooks/LSTM Multivariate Forecasting.ipynb
[NotebookApp | INFO] Saving file at /notebooks/LSTM Multivariate Forecasting.ipynb
[NotebookApp | INFO] Saving file at /notebooks/Calculate good quality data ratio.ipynb
[NotebookApp | INFO] Saving file at /notebooks/Calculate good quality data ratio.ipynb
[NotebookApp | INFO] Saving file at /notebooks/Calculate good quality data ratio.ipynb
[NotebookApp | INFO] Kernel restarted: e974a402-0fc1-4da6-b432-df33ed61b550
[NotebookApp | INFO] Kernel restarted: e974a402-0fc1-4da6-b432-df33ed61b550
[NotebookApp | INFO] Saving file at /notebooks/Calculate good quality data ratio.ipynb
[NotebookApp | INFO] Saving file at /notebooks/Calculate good quality data ratio.ipynb
[NotebookApp | INFO] Saving file at /notebooks/Calculate good quality data ratio.ipynb
[NotebookApp | INFO] Kernel restarted: e974a402-0fc1-4da6-b432-df33ed61b550
[NotebookApp | INFO] Saving file at /notebooks/Calculate good quality data ratio.ipynb
[NotebookApp | INFO] interrupted
[NotebookApp | CRITICAL] Shutdown confirmed
[NotebookApp | INFO] Shutting down kernels
[NotebookApp | INFO] Kernel shutdown: e974a402-0fc1-4da6-b432-df33ed61b550
[NotebookApp | INFO] Kernel shutdown: 452b11c6-2434-41b3-bbdc-467f9a8e2f37
[NotebookApp | INFO] Kernel shutdown: 20a0c79f-0cd2-48d8-a663-c265393b1960
[NotebookApp | INFO] Kernel shutdown: 8197d994-b182-4702-aafc-d0dff2cb9af5
[NotebookApp | WARNING] No nbgrader_config.py file found (rerun with --debug to see where nbgrader is looking)
[NotebookApp | INFO] Loading the validate_assignment nbgrader serverextension
[NotebookApp | INFO] Serving notebooks from local directory: /Users/sherryleo/Documents/course/Project with Ugur/healthcare-predictive
[NotebookApp | INFO] 0 active kernels 
[NotebookApp | INFO] The Jupyter Notebook is running at: http://localhost:8888/?token=e14ebc231c29422b01b24bd90ba91458c8c35d9a21f4fb54
[NotebookApp | INFO] Use Control-C to stop this server and shut down all kernels (twice to skip confirmation).
[NotebookApp | CRITICAL] 
    
    Copy/paste this URL into your browser when you connect for the first time,
    to login with a token:
        http://localhost:8888/?token=e14ebc231c29422b01b24bd90ba91458c8c35d9a21f4fb54
[NotebookApp | INFO] Accepting one-time-token-authenticated connection from ::1
[NotebookApp | WARNING] No nbgrader_config.py file found. Rerun with DEBUG log level to see where nbgrader is looking.
[NotebookApp | CRITICAL] Unwritable directory, please contact your instructor: /srv/nbgrader/exchange
[NotebookApp | ERROR] Traceback (most recent call last):
      File "/Users/sherryleo/anaconda/lib/python3.6/site-packages/nbgrader/server_extensions/assignment_list/handlers.py", line 63, in list_released_assignments
        assignments = lister.start()
      File "/Users/sherryleo/anaconda/lib/python3.6/site-packages/nbgrader/exchange/list.py", line 129, in start
        super(ExchangeList, self).start()
      File "/Users/sherryleo/anaconda/lib/python3.6/site-packages/nbgrader/exchange/exchange.py", line 122, in start
        self.ensure_root()
      File "/Users/sherryleo/anaconda/lib/python3.6/site-packages/nbgrader/exchange/exchange.py", line 100, in ensure_root
        self.fail("Unwritable directory, please contact your instructor: {}".format(self.root))
      File "/Users/sherryleo/anaconda/lib/python3.6/site-packages/nbgrader/exchange/exchange.py", line 78, in fail
        raise ExchangeError(msg)
    nbgrader.exchange.exchange.ExchangeError: Unwritable directory, please contact your instructor: /srv/nbgrader/exchange
    
[NotebookApp | WARNING] 404 GET /demo.gif (::1) 10.55ms referer=http://localhost:8888/tree
[NotebookApp | WARNING] No nbgrader_config.py file found. Rerun with DEBUG log level to see where nbgrader is looking.
[NotebookApp | CRITICAL] Unwritable directory, please contact your instructor: /srv/nbgrader/exchange
[NotebookApp | ERROR] Traceback (most recent call last):
      File "/Users/sherryleo/anaconda/lib/python3.6/site-packages/nbgrader/server_extensions/assignment_list/handlers.py", line 63, in list_released_assignments
        assignments = lister.start()
      File "/Users/sherryleo/anaconda/lib/python3.6/site-packages/nbgrader/exchange/list.py", line 129, in start
        super(ExchangeList, self).start()
      File "/Users/sherryleo/anaconda/lib/python3.6/site-packages/nbgrader/exchange/exchange.py", line 122, in start
        self.ensure_root()
      File "/Users/sherryleo/anaconda/lib/python3.6/site-packages/nbgrader/exchange/exchange.py", line 100, in ensure_root
        self.fail("Unwritable directory, please contact your instructor: {}".format(self.root))
      File "/Users/sherryleo/anaconda/lib/python3.6/site-packages/nbgrader/exchange/exchange.py", line 78, in fail
        raise ExchangeError(msg)
    nbgrader.exchange.exchange.ExchangeError: Unwritable directory, please contact your instructor: /srv/nbgrader/exchange
    
[NotebookApp | WARNING] 404 GET /tree/demo.gif (::1) 1.37ms referer=http://localhost:8888/tree/notebooks
[NotebookApp | INFO] Kernel started: f4634172-5c3a-44ce-8ef3-83b5138e9b2f
[NotebookApp | INFO] Saving file at /notebooks/Calculate good quality data ratio.ipynb
[NotebookApp | INFO] Saving file at /notebooks/Calculate good quality data ratio.ipynb
[NotebookApp | WARNING] WebSocket ping timeout after 7229998 ms.
[NotebookApp | INFO] interrupted
[NotebookApp | CRITICAL] Shutdown confirmed
[NotebookApp | INFO] Shutting down kernels
[NotebookApp | INFO] Kernel shutdown: f4634172-5c3a-44ce-8ef3-83b5138e9b2f
[NotebookApp | WARNING] No nbgrader_config.py file found (rerun with --debug to see where nbgrader is looking)
[NotebookApp | INFO] Loading the validate_assignment nbgrader serverextension
[NotebookApp | INFO] Serving notebooks from local directory: /Users/sherryleo/Documents/course/Project with Ugur/healthcare-predictive
[NotebookApp | INFO] 0 active kernels 
[NotebookApp | INFO] The Jupyter Notebook is running at: http://localhost:8888/?token=33beb861ddd339467eb6792dab539f7fb1cf61850fbf4bfc
[NotebookApp | INFO] Use Control-C to stop this server and shut down all kernels (twice to skip confirmation).
[NotebookApp | CRITICAL] 
    
    Copy/paste this URL into your browser when you connect for the first time,
    to login with a token:
        http://localhost:8888/?token=33beb861ddd339467eb6792dab539f7fb1cf61850fbf4bfc
[NotebookApp | INFO] Accepting one-time-token-authenticated connection from ::1
[NotebookApp | WARNING] No nbgrader_config.py file found. Rerun with DEBUG log level to see where nbgrader is looking.
[NotebookApp | CRITICAL] Unwritable directory, please contact your instructor: /srv/nbgrader/exchange
[NotebookApp | ERROR] Traceback (most recent call last):
      File "/Users/sherryleo/anaconda/lib/python3.6/site-packages/nbgrader/server_extensions/assignment_list/handlers.py", line 63, in list_released_assignments
        assignments = lister.start()
      File "/Users/sherryleo/anaconda/lib/python3.6/site-packages/nbgrader/exchange/list.py", line 129, in start
        super(ExchangeList, self).start()
      File "/Users/sherryleo/anaconda/lib/python3.6/site-packages/nbgrader/exchange/exchange.py", line 122, in start
        self.ensure_root()
      File "/Users/sherryleo/anaconda/lib/python3.6/site-packages/nbgrader/exchange/exchange.py", line 100, in ensure_root
        self.fail("Unwritable directory, please contact your instructor: {}".format(self.root))
      File "/Users/sherryleo/anaconda/lib/python3.6/site-packages/nbgrader/exchange/exchange.py", line 78, in fail
        raise ExchangeError(msg)
    nbgrader.exchange.exchange.ExchangeError: Unwritable directory, please contact your instructor: /srv/nbgrader/exchange
    
[NotebookApp | WARNING] 404 GET /demo.gif (::1) 16.84ms referer=http://localhost:8888/tree
[NotebookApp | WARNING] No nbgrader_config.py file found. Rerun with DEBUG log level to see where nbgrader is looking.
[NotebookApp | CRITICAL] Unwritable directory, please contact your instructor: /srv/nbgrader/exchange
[NotebookApp | ERROR] Traceback (most recent call last):
      File "/Users/sherryleo/anaconda/lib/python3.6/site-packages/nbgrader/server_extensions/assignment_list/handlers.py", line 63, in list_released_assignments
        assignments = lister.start()
      File "/Users/sherryleo/anaconda/lib/python3.6/site-packages/nbgrader/exchange/list.py", line 129, in start
        super(ExchangeList, self).start()
      File "/Users/sherryleo/anaconda/lib/python3.6/site-packages/nbgrader/exchange/exchange.py", line 122, in start
        self.ensure_root()
      File "/Users/sherryleo/anaconda/lib/python3.6/site-packages/nbgrader/exchange/exchange.py", line 100, in ensure_root
        self.fail("Unwritable directory, please contact your instructor: {}".format(self.root))
      File "/Users/sherryleo/anaconda/lib/python3.6/site-packages/nbgrader/exchange/exchange.py", line 78, in fail
        raise ExchangeError(msg)
    nbgrader.exchange.exchange.ExchangeError: Unwritable directory, please contact your instructor: /srv/nbgrader/exchange
    
[NotebookApp | WARNING] 404 GET /tree/demo.gif (::1) 1.63ms referer=http://localhost:8888/tree/notebooks
[NotebookApp | INFO] Kernel started: 92ca9fbc-e958-4b8f-87f9-9db873ebb787
[NotebookApp | INFO] 302 GET /notebooks/Calculate%20good%20quality%20data%20ratio.ipynb (::1) 20.82ms
[NotebookApp | INFO] Kernel started: e968df60-9cdd-4fde-b196-67485abfb895
[NotebookApp | INFO] Saving file at /notebooks/Slice data from alarms.ipynb
[NotebookApp | INFO] Kernel restarted: e968df60-9cdd-4fde-b196-67485abfb895
[NotebookApp | INFO] Kernel interrupted: e968df60-9cdd-4fde-b196-67485abfb895
[NotebookApp | INFO] Kernel restarted: e968df60-9cdd-4fde-b196-67485abfb895
[NotebookApp | INFO] Saving file at /notebooks/Slice data from alarms.ipynb
[NotebookApp | INFO] Saving file at /notebooks/Slice data from alarms.ipynb
[NotebookApp | INFO] Saving file at /notebooks/Slice data from alarms.ipynb
[NotebookApp | INFO] Saving file at /notebooks/Slice data from alarms.ipynb
[NotebookApp | INFO] Saving file at /notebooks/Slice data from alarms.ipynb
[NotebookApp | INFO] Kernel restarted: e968df60-9cdd-4fde-b196-67485abfb895
[NotebookApp | INFO] Saving file at /notebooks/Slice data from alarms.ipynb
[NotebookApp | INFO] Saving file at /notebooks/Slice data from alarms.ipynb
[NotebookApp | INFO] Saving file at /notebooks/Slice data from alarms.ipynb
[NotebookApp | INFO] Saving file at /notebooks/Slice data from alarms.ipynb
[NotebookApp | INFO] Saving file at /notebooks/Slice data from alarms.ipynb
[NotebookApp | INFO] Saving file at /notebooks/Slice data from alarms.ipynb
[NotebookApp | INFO] Saving file at /notebooks/Slice data from alarms.ipynb
[NotebookApp | INFO] Kernel restarted: e968df60-9cdd-4fde-b196-67485abfb895
[NotebookApp | INFO] Saving file at /notebooks/Slice data from alarms.ipynb
[NotebookApp | INFO] Saving file at /notebooks/Slice data from alarms.ipynb
[NotebookApp | INFO] Saving file at /notebooks/Slice data from alarms.ipynb
[NotebookApp | INFO] Saving file at /notebooks/Slice data from alarms.ipynb
[NotebookApp | INFO] Kernel restarted: e968df60-9cdd-4fde-b196-67485abfb895
[NotebookApp | INFO] Saving file at /notebooks/Slice data from alarms.ipynb
[NotebookApp | INFO] Saving file at /notebooks/Slice data from alarms.ipynb
[NotebookApp | INFO] Saving file at /notebooks/Slice data from alarms.ipynb
[NotebookApp | INFO] Kernel restarted: e968df60-9cdd-4fde-b196-67485abfb895
[NotebookApp | INFO] Saving file at /notebooks/Slice data from alarms.ipynb
[NotebookApp | INFO] Saving file at /notebooks/Slice data from alarms.ipynb
[NotebookApp | INFO] Saving file at /notebooks/Slice data from alarms.ipynb
[NotebookApp | INFO] Saving file at /notebooks/Slice data from alarms.ipynb
[NotebookApp | INFO] Saving file at /notebooks/Slice data from alarms.ipynb
[NotebookApp | INFO] Kernel restarted: e968df60-9cdd-4fde-b196-67485abfb895
[NotebookApp | INFO] Saving file at /notebooks/Slice data from alarms.ipynb
[NotebookApp | INFO] Saving file at /notebooks/Slice data from alarms.ipynb
[NotebookApp | INFO] Saving file at /notebooks/Slice data from alarms.ipynb
[NotebookApp | INFO] Kernel started: c3713cb2-6b9a-4af7-a983-4c29c3e51a69
[NotebookApp | INFO] Saving file at /notebooks/Slice data from alarms.ipynb
[NotebookApp | INFO] Saving file at /notebooks/Slice data from alarms.ipynb
[NotebookApp | INFO] Saving file at /notebooks/Slice data from alarms.ipynb
[NotebookApp | INFO] Saving file at /notebooks/Slice data from alarms.ipynb
[NotebookApp | INFO] Saving file at /notebooks/Slice data from alarms.ipynb
[NotebookApp | INFO] Saving file at /notebooks/Slice data from alarms.ipynb
[NotebookApp | INFO] Saving file at /notebooks/Slice data from alarms.ipynb
[NotebookApp | INFO] interrupted
[NotebookApp | CRITICAL] Shutdown confirmed
[NotebookApp | INFO] Shutting down kernels
[NotebookApp | INFO] Kernel shutdown: 92ca9fbc-e958-4b8f-87f9-9db873ebb787
[NotebookApp | INFO] Kernel shutdown: e968df60-9cdd-4fde-b196-67485abfb895
[NotebookApp | INFO] Kernel shutdown: c3713cb2-6b9a-4af7-a983-4c29c3e51a69
[NotebookApp | WARNING] No nbgrader_config.py file found (rerun with --debug to see where nbgrader is looking)
[NotebookApp | INFO] Loading the validate_assignment nbgrader serverextension
[NotebookApp | INFO] Serving notebooks from local directory: /Users/sherryleo/Documents/course/Project with Ugur/healthcare-predictive
[NotebookApp | INFO] 0 active kernels 
[NotebookApp | INFO] The Jupyter Notebook is running at: http://localhost:8888/?token=59f4561218d28532483af58a812cdf99ac71b92c48859d2b
[NotebookApp | INFO] Use Control-C to stop this server and shut down all kernels (twice to skip confirmation).
[NotebookApp | CRITICAL] 
    
    Copy/paste this URL into your browser when you connect for the first time,
    to login with a token:
        http://localhost:8888/?token=59f4561218d28532483af58a812cdf99ac71b92c48859d2b
[NotebookApp | INFO] Accepting one-time-token-authenticated connection from ::1
[NotebookApp | WARNING] No nbgrader_config.py file found. Rerun with DEBUG log level to see where nbgrader is looking.
[NotebookApp | CRITICAL] Unwritable directory, please contact your instructor: /srv/nbgrader/exchange
[NotebookApp | ERROR] Traceback (most recent call last):
      File "/Users/sherryleo/anaconda/lib/python3.6/site-packages/nbgrader/server_extensions/assignment_list/handlers.py", line 63, in list_released_assignments
        assignments = lister.start()
      File "/Users/sherryleo/anaconda/lib/python3.6/site-packages/nbgrader/exchange/list.py", line 129, in start
        super(ExchangeList, self).start()
      File "/Users/sherryleo/anaconda/lib/python3.6/site-packages/nbgrader/exchange/exchange.py", line 122, in start
        self.ensure_root()
      File "/Users/sherryleo/anaconda/lib/python3.6/site-packages/nbgrader/exchange/exchange.py", line 100, in ensure_root
        self.fail("Unwritable directory, please contact your instructor: {}".format(self.root))
      File "/Users/sherryleo/anaconda/lib/python3.6/site-packages/nbgrader/exchange/exchange.py", line 78, in fail
        raise ExchangeError(msg)
    nbgrader.exchange.exchange.ExchangeError: Unwritable directory, please contact your instructor: /srv/nbgrader/exchange
    
[NotebookApp | WARNING] 404 GET /demo.gif (::1) 12.29ms referer=http://localhost:8888/tree
[NotebookApp | WARNING] No nbgrader_config.py file found. Rerun with DEBUG log level to see where nbgrader is looking.
[NotebookApp | CRITICAL] Unwritable directory, please contact your instructor: /srv/nbgrader/exchange
[NotebookApp | ERROR] Traceback (most recent call last):
      File "/Users/sherryleo/anaconda/lib/python3.6/site-packages/nbgrader/server_extensions/assignment_list/handlers.py", line 63, in list_released_assignments
        assignments = lister.start()
      File "/Users/sherryleo/anaconda/lib/python3.6/site-packages/nbgrader/exchange/list.py", line 129, in start
        super(ExchangeList, self).start()
      File "/Users/sherryleo/anaconda/lib/python3.6/site-packages/nbgrader/exchange/exchange.py", line 122, in start
        self.ensure_root()
      File "/Users/sherryleo/anaconda/lib/python3.6/site-packages/nbgrader/exchange/exchange.py", line 100, in ensure_root
        self.fail("Unwritable directory, please contact your instructor: {}".format(self.root))
      File "/Users/sherryleo/anaconda/lib/python3.6/site-packages/nbgrader/exchange/exchange.py", line 78, in fail
        raise ExchangeError(msg)
    nbgrader.exchange.exchange.ExchangeError: Unwritable directory, please contact your instructor: /srv/nbgrader/exchange
    
[NotebookApp | WARNING] 404 GET /tree/demo.gif (::1) 1.84ms referer=http://localhost:8888/tree/notebooks
[NotebookApp | WARNING] Notebook notebooks/Slice data from alarms - for Goal2.ipynb is not trusted
[NotebookApp | INFO] Kernel started: 4b325cb5-2b29-429a-a7ae-e04b151b61b1
[NotebookApp | INFO] Kernel started: 2afd3442-6d94-4124-8f68-1f0473dba4a8
[NotebookApp | INFO] Kernel started: e0c9d570-f5c1-4f6c-8b19-f1f8d8d1df7d
[NotebookApp | INFO] Saving file at /notebooks/Slice data from alarms - for Goal2.ipynb
[NotebookApp | WARNING] Saving untrusted notebook notebooks/Slice data from alarms - for Goal2.ipynb
[NotebookApp | INFO] Saving file at /notebooks/Slice data from alarms - for Goal2.ipynb
[NotebookApp | WARNING] Saving untrusted notebook notebooks/Slice data from alarms - for Goal2.ipynb
[NotebookApp | INFO] Kernel restarted: 4b325cb5-2b29-429a-a7ae-e04b151b61b1
[NotebookApp | INFO] Saving file at /notebooks/Slice data from alarms - for Goal2.ipynb
[NotebookApp | INFO] Saving file at /notebooks/Slice data from alarms - for Goal2.ipynb
[NotebookApp | INFO] Saving file at /notebooks/Slice data from alarms - for Goal2.ipynb
[NotebookApp | INFO] Saving file at /notebooks/Slice data from alarms - for Goal2.ipynb
[NotebookApp | INFO] Saving file at /notebooks/LSTM on sliced datastream.ipynb
[NotebookApp | INFO] Saving file at /notebooks/LSTM on sliced datastream.ipynb
[NotebookApp | INFO] Saving file at /notebooks/LSTM on sliced datastream.ipynb
[NotebookApp | INFO] Saving file at /notebooks/LSTM on sliced datastream.ipynb
[NotebookApp | INFO] Kernel interrupted: e0c9d570-f5c1-4f6c-8b19-f1f8d8d1df7d
[NotebookApp | INFO] Saving file at /notebooks/LSTM on sliced datastream.ipynb
[NotebookApp | INFO] Saving file at /notebooks/LSTM on sliced datastream.ipynb
[NotebookApp | INFO] Saving file at /notebooks/LSTM on sliced datastream.ipynb
[NotebookApp | INFO] Saving file at /notebooks/LSTM on sliced datastream.ipynb
[NotebookApp | INFO] Saving file at /notebooks/LSTM on sliced datastream.ipynb
[NotebookApp | INFO] Saving file at /notebooks/LSTM on sliced datastream.ipynb
[NotebookApp | INFO] Saving file at /notebooks/LSTM on sliced datastream.ipynb
[NotebookApp | INFO] Saving file at /notebooks/LSTM on sliced datastream.ipynb
[NotebookApp | INFO] Saving file at /notebooks/LSTM on sliced datastream.ipynb
[NotebookApp | INFO] Saving file at /notebooks/LSTM on sliced datastream.ipynb
[NotebookApp | INFO] Saving file at /notebooks/LSTM on sliced datastream.ipynb
[NotebookApp | INFO] Saving file at /notebooks/LSTM on sliced datastream.ipynb
[NotebookApp | INFO] 302 GET /notebooks/Calculate%20good%20quality%20data%20ratio.ipynb (::1) 39.62ms
[NotebookApp | INFO] Saving file at /notebooks/LSTM on sliced datastream.ipynb
[NotebookApp | INFO] Kernel restarted: e0c9d570-f5c1-4f6c-8b19-f1f8d8d1df7d
[NotebookApp | INFO] Saving file at /notebooks/LSTM on sliced datastream.ipynb
[NotebookApp | INFO] Saving file at /notebooks/LSTM on sliced datastream.ipynb
[NotebookApp | INFO] Saving file at /notebooks/LSTM on sliced datastream.ipynb
[NotebookApp | INFO] Saving file at /notebooks/LSTM on sliced datastream.ipynb
[NotebookApp | INFO] Saving file at /notebooks/LSTM on sliced datastream.ipynb
[NotebookApp | INFO] Saving file at /notebooks/LSTM on sliced datastream.ipynb
[NotebookApp | INFO] Saving file at /notebooks/LSTM on sliced datastream.ipynb
[NotebookApp | INFO] Saving file at /notebooks/LSTM on sliced datastream.ipynb
[NotebookApp | INFO] Saving file at /notebooks/LSTM on sliced datastream.ipynb
[NotebookApp | INFO] Saving file at /notebooks/LSTM on sliced datastream.ipynb
[NotebookApp | INFO] Saving file at /notebooks/LSTM on sliced datastream.ipynb
[NotebookApp | INFO] Saving file at /notebooks/LSTM on sliced datastream.ipynb
[NotebookApp | INFO] Kernel started: 55eaa707-1c43-4cda-8e5b-957ffff45b9c
[NotebookApp | INFO] 302 GET /notebooks/Calculate%20good%20quality%20data%20ratio.ipynb (::1) 7.30ms
[NotebookApp | INFO] 302 GET /notebooks/Calculate%20good%20quality%20data%20ratio.ipynb (::1) 5.07ms
[NotebookApp | INFO] Kernel started: 757662d8-70ba-4f0f-9629-cae44d5b18ad
[NotebookApp | INFO] Saving file at /notebooks/Preprocessing original time series data.ipynb
[NotebookApp | INFO] Kernel restarted: 757662d8-70ba-4f0f-9629-cae44d5b18ad
[NotebookApp | INFO] Saving file at /notebooks/Preprocessing original time series data.ipynb
[NotebookApp | INFO] Saving file at /notebooks/Preprocessing original time series data.ipynb
[NotebookApp | INFO] Saving file at /notebooks/Preprocessing original time series data.ipynb
[NotebookApp | INFO] Saving file at /notebooks/Preprocessing original time series data.ipynb
[NotebookApp | INFO] Saving file at /notebooks/Preprocessing original time series data.ipynb
[NotebookApp | INFO] Saving file at /notebooks/Preprocessing original time series data.ipynb
[NotebookApp | INFO] Kernel restarted: 757662d8-70ba-4f0f-9629-cae44d5b18ad
[NotebookApp | INFO] Saving file at /notebooks/Preprocessing original time series data.ipynb
[NotebookApp | INFO] Saving file at /notebooks/Preprocessing original time series data.ipynb
[NotebookApp | INFO] Saving file at /notebooks/Preprocessing original time series data.ipynb
[NotebookApp | INFO] Saving file at /notebooks/Preprocessing original time series data.ipynb
[NotebookApp | INFO] Saving file at /notebooks/Preprocessing original time series data.ipynb
[NotebookApp | INFO] Saving file at /notebooks/Preprocessing original time series data.ipynb
[NotebookApp | INFO] Saving file at /notebooks/Preprocessing original time series data.ipynb
[NotebookApp | INFO] Saving file at /notebooks/Preprocessing original time series data.ipynb
[NotebookApp | INFO] Saving file at /notebooks/Preprocessing original time series data.ipynb
[NotebookApp | INFO] Saving file at /notebooks/Preprocessing original time series data.ipynb
[NotebookApp | INFO] Saving file at /notebooks/Slice data from alarms - for Goal2.ipynb
[NotebookApp | INFO] Saving file at /notebooks/Slice data from alarms - for Goal2.ipynb
[NotebookApp | INFO] Saving file at /notebooks/Slice data from alarms - for Goal2.ipynb
[NotebookApp | INFO] Saving file at /notebooks/Preprocess and QoS shifting.ipynb
[NotebookApp | INFO] Creating new notebook in /notebooks
[NotebookApp | INFO] Kernel started: 9730c8b8-53d9-4428-8b4b-070d78414dab
[NotebookApp | INFO] Saving file at /notebooks/Preprocess without aggregation.ipynb
[NotebookApp | INFO] Saving file at /notebooks/Preprocess without aggregation.ipynb
[NotebookApp | INFO] Saving file at /notebooks/Preprocess without aggregation.ipynb
[NotebookApp | INFO] Saving file at /notebooks/Preprocess without aggregation.ipynb
[NotebookApp | INFO] Saving file at /notebooks/Preprocess without aggregation.ipynb
[NotebookApp | INFO] interrupted
[NotebookApp | CRITICAL] Shutdown confirmed
[NotebookApp | INFO] Shutting down kernels
[NotebookApp | INFO] Kernel shutdown: 4b325cb5-2b29-429a-a7ae-e04b151b61b1
[NotebookApp | INFO] Kernel shutdown: 2afd3442-6d94-4124-8f68-1f0473dba4a8
[NotebookApp | INFO] Kernel shutdown: e0c9d570-f5c1-4f6c-8b19-f1f8d8d1df7d
[NotebookApp | INFO] Kernel shutdown: 55eaa707-1c43-4cda-8e5b-957ffff45b9c
[NotebookApp | INFO] Kernel shutdown: 757662d8-70ba-4f0f-9629-cae44d5b18ad
[NotebookApp | INFO] Kernel shutdown: 9730c8b8-53d9-4428-8b4b-070d78414dab
